export const COLLECTIONS = {
  PRODUCTS: 'products',
  INVENTORY: 'inventory',
  BOMS: 'boms',
  MANUFACTURING_ORDERS: 'manufacturingOrders',
  SALES_ORDERS: 'salesOrders',
  INVOICES: 'invoices',
  CUSTOMERS: 'customers',
  VENDORS: 'vendors',
  PURCHASE_ORDERS: 'purchaseOrders',
  RFQS: 'rfqs',
  PRICING_RULES: 'pricingRules',
  QUALITY_CHECKS: 'qualityChecks',
  STOCK_MOVES: 'stockMoves',
  EMPLOYEES: 'employees',
  ACCOUNTS: 'accounts',
  JOURNAL_ENTRIES: 'journalEntries',
  BANK_STATEMENTS: 'bankStatements',
  PAYMENTS: 'payments',
} as const;